[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

# Proxy para la API de Render
[[redirects]]
  from = "/api/*"
  to = "https://spotidownloader-backend.onrender.com/api/:splat"
  status = 200

# Redirecci√≥n para SPA (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
